name: aims_mobile
description: PHIA Monitoring tool.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.30+39

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_bluetooth_serial: ^0.2.2
  google_fonts: ^0.2.0
  flutter:
    sdk: flutter
  json_to_form: "^0.0.1"
  intl: ^0.16.1
  moor_flutter: ^3.1.0
  sqlite3_flutter_libs: # Also use the latest version.
  path_provider:
  open_file: ^3.0.3
  syncfusion_flutter_pdf: ^19.1.59-beta
  universal_html: ^1.2.4
  path:
  geolocator: ^6.1.2
  syncfusion_flutter_signaturepad:
  #firebase_crashlytics: "^0.2.4"
  modal_progress_hud: ^0.1.3
  firebase_core: ^0.4.0
  firebase_auth: ^0.11.1+6
#  package_info_plus: ^0.6.3
  package_info: ^0.4.3+4
  google_sign_in: ^4.0.1+3
  undo: ^1.3.0+1
  bloc: ^6.0.3
  flutter_bloc: ^6.0.5
  firebase_messaging: ^6.0.16
  get_it: ^4.0.2
  cloud_firestore: ^0.12.9+5



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  cached_network_image: ^2.2.0+1
  material_design_icons_flutter: ^4.0.5345
  device_info: ^0.4.2+9
  location: ^3.0.0
  shared_preferences: ^0.5.12+4
  font_awesome_flutter:
  progress_dialog: ^1.2.4
  ext_storage:
  cloud_functions: ^0.5.0
  percent_indicator: ^3.0.1
  #msal_js: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_sound:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  msal_mobile: ^0.1.4
#  font_awesome_flutter: ^8.2.0
#  cupertino_icons: ^1.0.0
#  path_provider:
#  path:
  image_gallery_saver:
  permission_handler: ^3.3.0
#  audioplayers:
  flutter_better_camera:
  video_player: ^0.10.0
  e2e: "^0.2.0"
  moor_generator: # use the latest version
  build_runner:
  dio: 3.0.9
  http: ^0.12.2
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/auth_config.json
    - assets/notification.png
    - assets/setting.png
    - assets/todo.png
    - assets/logout.png
    - assets/update.ico
    - assets/landing.webp
    - assets/bluetooth.png
    - assets/message.png
    - assets/home.png
    - assets/supervisor.png
    - assets/camera.png
    - assets/audio.png
    - assets/drawer_header_background.png
    - assets/Picture1.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
